"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { LockKeyhole } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { AuthShell } from "@/components/auth-shell";
import { backend, errorMessage } from "@/lib/api";

export default function ResetPasswordPage(){const{key}=useParams<{key:string}>();const router=useRouter();const[valid,setValid]=useState<boolean>();const[error,setError]=useState("");const[busy,setBusy]=useState(false);useEffect(()=>{backend("_allauth/browser/v1/auth/password/reset",{headers:{"X-Password-Reset-Key":key}}).then(()=>setValid(true)).catch(reason=>{setError(errorMessage(reason));setValid(false)})},[key]);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);if(data.get("password")!==data.get("confirm")){setError("The passwords do not match.");setBusy(false);return}try{await backend("_allauth/browser/v1/auth/password/reset",{method:"POST",body:JSON.stringify({key,password:data.get("password")})});router.replace("/login?reset=complete")}catch(reason){setError(errorMessage(reason));setBusy(false)}}return <AuthShell title="Choose a fresh, strong password."><div className="auth-card"><h1 className="display">Set a new password.</h1><p>This reset link is checked before a password can be changed.</p>{error&&<div className="form-alert error">{error}</div>}{valid===undefined&&<div className="skeleton"/>}{valid&&<form className="form-grid" onSubmit={submit}><div className="field"><label htmlFor="password">New password</label><div className="input-wrap"><LockKeyhole className="field-icon" size={18}/><input className="input has-icon" id="password" name="password" type="password" autoComplete="new-password" minLength={8} required/></div></div><div className="field"><label htmlFor="confirm">Confirm new password</label><input className="input" id="confirm" name="confirm" type="password" autoComplete="new-password" required/></div><button className="btn btn-primary btn-full" disabled={busy}>{busy?"Updating…":"Update password"}</button></form>}{valid===false&&<p><Link className="auth-link" href="/forgot-password">Request a new reset link</Link></p>}</div></AuthShell>}
