"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { AtSign, LockKeyhole, Mail } from "lucide-react";
import { useRouter } from "next/navigation";
import { AuthShell } from "@/components/auth-shell";
import { SocialButtons } from "@/components/social-buttons";
import { AuthResponse, backend, errorMessage } from "@/lib/api";

export default function SignupPage() {
  const router = useRouter();
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [strength,setStrength]=useState(0);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const data=new FormData(event.currentTarget);try{const result=await backend<AuthResponse>("_allauth/browser/v1/auth/signup",{method:"POST",body:JSON.stringify({username:String(data.get("username")??"").trim(),email:String(data.get("email")??"").trim(),password:data.get("password"),password_confirm:data.get("password_confirm"),terms:data.get("terms")==="on"})});if(!result.meta?.is_authenticated)throw new Error("Your account needs an additional verification step.");router.replace("/dashboard");router.refresh();}catch(reason){setError(errorMessage(reason));setBusy(false)}}
  function score(value:string){setStrength([8,10,12,15].filter((length)=>value.length>=length).length)}
  return <AuthShell title="One account. Every media workflow."><div className="auth-card"><h1 className="display">Create your space.</h1><p>Your first secure API key is a minute away.</p>{error&&<div className="form-alert error" role="alert">{error}</div>}<form className="form-grid" onSubmit={submit} style={{marginTop:18}}><div className="field"><label htmlFor="username">Username</label><div className="input-wrap"><AtSign className="field-icon" size={18}/><input className="input has-icon" id="username" name="username" autoComplete="username" minLength={3} required placeholder="studio_name"/></div></div><div className="field"><label htmlFor="email">Work email</label><div className="input-wrap"><Mail className="field-icon" size={18}/><input className="input has-icon" id="email" name="email" type="email" autoComplete="email" required placeholder="you@company.com"/></div></div><div className="field"><label htmlFor="password">Password</label><div className="input-wrap"><LockKeyhole className="field-icon" size={18}/><input className="input has-icon" id="password" name="password" type="password" autoComplete="new-password" minLength={8} required onChange={e=>score(e.target.value)} placeholder="8+ characters"/></div><div className="password-score" role="meter" aria-label="Password strength" aria-valuemin={0} aria-valuemax={4} aria-valuenow={strength}>{[1,2,3,4].map(level=><i className={level<=strength?"on":""} key={level}/>)}</div></div><div className="field"><label htmlFor="password_confirm">Confirm password</label><input className="input" id="password_confirm" name="password_confirm" type="password" autoComplete="new-password" required/></div><label className="check"><input type="checkbox" name="terms" required/><span>I agree to the <Link className="auth-link" href="/terms">Terms</Link> and <Link className="auth-link" href="/privacy">Privacy Policy</Link>.</span></label><button className="btn btn-primary btn-full" disabled={busy}>{busy?"Creating account…":"Create free account"}</button></form><SocialButtons onError={setError}/><p style={{textAlign:"center",marginTop:24,color:"var(--muted)"}}>Already have an account? <Link className="auth-link" href="/login">Sign in</Link></p></div></AuthShell>;
}
